### ISSUE TITLE
Navbar Problem

### ISSUE THREAD

**Issue by BasiliusFleischlein** [SuperPommeDeTerre/WoTClanTool#13] opened 2017-07-28 07:58 UTC
I installed the WoTClanTool and it works fine but i have one Problem with the Navbar(and all links that are used in the ClanTool) it sends me not to a PHP Site.

For Example i go to Admin Settings and it dont open "/admin.php" it send me to "/admin" and it do that with all Sites except the Links that go on external site like github.

I got the Error "The requested URL /WoTClanTool/home was not found on this server."

Where i can find the links to change it manualy?

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 08:18
Hi, this works as intended. In fact, this app use Apache mod_rewrite in order to suppress the .php file extension.
You can see it in your .htaccess file which is located at the root of your installation.

**Comment by BasiliusFleischlein** [comment] 2017-07-28 08:21
You mean the .htaccess in "WoTClanTool"? or one other?

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 08:24
Yes, this one. It is generated by the installation process. It is based on the template .htacces.template.

**Comment by BasiliusFleischlein** [comment] 2017-07-28 08:27
`DirectoryIndex index.php
#Options -Multiviews
<IfModule mod_rewrite.c>
	RewriteEngine on
	RewriteBase /WoTClanTool/
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-l
	RewriteRule ^strats/(.+)/(.+)$					strats.php?action=$1&view=$2				[QSA,PT,L]
	RewriteRule ^strats/(.+)$						strats.php?action=$1						[QSA,PT,L]
	RewriteRule ^encyclopedia/(.+)$					encyclopedia.php#$1							[QSA,PT,L]
	RewriteRule ^locales/resources/(.+)/(.+).json$	locales/resources.php?a=get&lng=$1&ns=$2	[QSA,PT,L]
	RewriteRule ^([a-zA-Z0-9]+)$					$1.php										[QSA,PT,L]
</IfModule>
`

**Comment by BasiliusFleischlein** [comment] 2017-07-28 08:27
thats what my .htaccess looks like

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 08:44
Could you give me the URL of your installation ?

**Comment by BasiliusFleischlein** [comment] 2017-07-28 08:51
www.42doa.de/WoTClanTool/

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 09:52
All seems fine...
Have you mod_rewrite enabled on your hosting ?

**Comment by BasiliusFleischlein** [comment] 2017-07-28 10:58
yes mod_rewrite is enabled - i found the problem, its that it cant access the htaccess file but i dont know how to fix it. I have changed my 000-default.conf in sites_avaiable and it brings a 500 Error i know that i must make
```
	<Directory /var/www/>
		Options Indexes FollowSymLinks MultiViews
		AllowOverride None
		Order allow,deny
		allow from all
	</Directory>
```
but dont know where to write it

**Comment by BasiliusFleischlein** [comment] 2017-07-28 12:17
got this message in the error.log of apache "/var/www/html/WoTClanTool/.htaccess: DirectoryIndex not allowed here"

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 13:07
I think you must write this in your Apache configuration files.
but you must have `AllowOverride All` IMHO.

**Comment by BasiliusFleischlein** [comment] 2017-07-28 13:11
```
<VirtualHost *:80>
        ServerName 42doa.de        
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/WoTClanTool/
        <Directory /var/www/html/WoTClanTool/>
                Options FollowSymLinks Indexes MultiViews
                AllowOverride All
                order allow,deny
                allow from all
        </Directory>
        ErrorLog /var/log/apache2/error.log
        LogLevel warn
        CustomLog /var/log/apache2/access.log combined
        ServerSignature On
</VirtualHost>
```

this is the part of my config for the WoTClanTool

the only think that not work is the rewrite :(

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 14:29
Sadly, I can't help you further, because I think it's mod_rewrite not loaded under your configuration.
Perhaps have a looks at your mod enabled configuration.
In case of emergency (if you can't make your Apache config working), you can use my instance : http://wot.pixbuf.net/wct/

**Comment by BasiliusFleischlein** [comment] 2017-07-28 15:15
thnx but i make it most of it working - i changed in the header.php and the footer.php the links to *.php and now it makes just with the login on the index.php and the logout problems

after login with WoT Account it sends me to /WoTClanTool/ and i dont know how to change it to send me to home.php
and after clicking on logout it sends me to /logout and not to logout.php

**Comment by SuperPommeDeTerre** [comment] 2017-07-28 15:45
Yeah, my code is a little messy about this.
There are PHP redirects and AJAX calls in Javascript code that must be changed also...

**Comment by BasiliusFleischlein** [comment] 2017-08-01 10:28
I fixed it - something went wrong with the apache2 user *facepalm*

**Comment by SuperPommeDeTerre** [comment] 2017-08-14 12:23
Thanks for informing ! Closing the issue.

**Closed by SuperPommeDeTerre** 2017-08-14 12:23 UTC
Labels: help wanted, question
